### ISSUE TITLE
瞬间表情被遮挡

### ISSUE THREAD

**Issue by yushuiguozhi** [halo-sigs/plugin-moments#104]
![企业微信截图_20240瞬间](https://github.com/halo-sigs/plugin-moments/assets/100274978/c09142fa-a198-4ca2-ac0f-a59800827091)

**Comment by LIlGG** [comment]
这是由于主题适配评论插件的问题，与 moment 无关。

see https://github.com/halo-dev/plugin-comment-widget/issues/76
/close
