### ISSUE TITLE
开放API Public相关接口没有moments相关的接口

### ISSUE THREAD

**Issue by liub1934** [halo-sigs/plugin-moments#123]
我看了下开放API Public相关接口没有moments相关的接口，希望能够加上。
https://demo.halo.run/webjars/swagger-ui/index.html?urls.primaryName=Public+API+V1alpha1

**Comment by LIlGG** [comment]
可能是 `demo.halo.run` 并没有安装瞬间插件。

moments 接口如下所示：

<img width="1534" alt="image" src="https://github.com/user-attachments/assets/cd63389f-922e-430a-bab5-f100f0499b37">
