### ISSUE TITLE
安装插件后，访问/moments，页面一直在等待状态

### ISSUE THREAD

**Issue by L-fw** [halo-sigs/plugin-moments#13]
halo中的配置文件的信息：
![image](https://user-images.githubusercontent.com/114651359/230574624-b697309c-cfb9-4b40-a32c-0fc5531181ba.png)
控制台组建可以正常使用：
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/114651359/230574899-cc2c444a-49dd-4d64-aed0-b0f439986a46.png">
但是访问/moments 的时候，浏览器在转圈圈：
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/114651359/230575522-99bbb7ee-3325-47b1-a443-571967b48fa0.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/114651359/230575882-878e6a09-0dbc-409f-bd65-21fdf92f8798.png">
主题/templates目录下也加了moments.html
![image](https://user-images.githubusercontent.com/114651359/230576244-0847f3d0-e479-4a0d-9c3f-f8a6ea0cc520.png)

**Comment by L-fw** [comment]
后台报错的信息是：
![image](https://user-images.githubusercontent.com/114651359/230576757-afa3f45c-dc89-4d1a-a8b1-c33a1982c19e.png)

**Comment by LIlGG** [comment]
请提供一下所运行的环境，例如 Halo 版本，插件版本。

**Comment by L-fw** [comment]
哦哦抱歉，原来的halo版本是2.3的，刚刚更新成2.4没问题了。

**Comment by LIlGG** [comment]
问题已经解决，关闭 issue。如果还有其他问题可以再创建新的 issue。 /close
