### ISSUE TITLE
在控制台新增瞬间，控制台不显示，前台页面也不显示

### ISSUE THREAD

**Issue by ghost** [halo-sigs/plugin-moments#135]
在控制台新增瞬间，控制台不显示，前台页面也不显示
使用的PG数据库 halo版本为最新版本 插件版本也为最新版本 主题使用的是 Walker1.12.1
![Image](https://github.com/user-attachments/assets/93ea86bc-34a5-47d6-b31e-0415a124094b)
![Image](https://github.com/user-attachments/assets/eda203c2-c3f7-46af-93e2-358b1965bc07)
![Image](https://github.com/user-attachments/assets/909eace3-48b2-4365-a58d-370e090de0f0)
![Image](https://github.com/user-attachments/assets/a411fc25-cf85-4fae-80e5-ce2aaf1bf52b)
@ruibaby

**Comment by ruibaby** [comment]
没有复现这个问题，能确保创建接口正常调用了吗？看看 Response 呢

**Comment by ruibaby** [comment]
halo 不会输出 nil 这样的内容，建议不经过任何代理，直接访问 Halo 的端口试试。
