### ISSUE TITLE
希望支持标签功能

### ISSUE THREAD

**Issue by guqing** [halo-sigs/plugin-moments#14]
支持通过标签关联 moment，并能通过
最好是内容中包含 `#标签` 则自动创建或关联标签功能

**Comment by LIlGG** [comment]
/assign

很不错的建议，当 moment 过多时，确实需要一个标签来进行筛选。

初步构想，用户在编辑 moment 时，可以输入 `#标签` 来创建/关联标签。为了与正常内容中的`#`符号分离，标签前后需要额外增加一个空格，如 `xxx #标签 xxx`，可以存在多级标签，例如 `xxx #标签1/标签2`。生成的标签可以用于 moment 内容筛选。

为了达成上述功能效果，大致需要如下 todo：
1、增加一个 Tag 数据模型，用于存放所有的标签。
2、moment 模型中增加一个 tags 属性，用于保存关联的 tags。
3、在 `moments` 路由中，增加 `tags` 页面变量，用于获取所有的 tag，待定是否加入 `moments?tag=xxx` 路由。
4、在 `finder` 中增加根据 tag 获取 moments 的接口，并补充先有接口。
5、自定义接口过滤条件中，增加 tag 过滤条件。
6、新增/修改 moments 时，获取其下所有的标签，并与现有标签进行关联，不存在标签则进行新建。
7、console 端使用编辑器功能识别标签（通过接口调用的，直接往接口中添加标签即可）
8、console 端增加 router `moments?tag=xxx`，用于筛选。
9、console 端增加删除 tag 功能。

**Comment by wan92hen** [comment]
这样就有两套标签数据了，不能直接复用文章的标签进行管理吗？

**Comment by guqing** [comment]
> 这样就有两套标签数据了，不能直接复用文章的标签进行管理吗？

文章的标签与 Moment 的标签有些作用应该是不同的，比如 Moment 的标签下没有 Moment 则标签也就不存在了，但文章不同，我的建议是 Moment 不在有标签自定义模型，而只是在对应的 Moment 的 labels 中包含标签即可，这样不用在维护标签也没有带来实质性好处，当 Moment 被删除时对应的标签自然就不存在了，由于现在是使用的自定义模型它区别于常规的关系型模型不与物理表挂钩，当没有标签自定义模型时更新创建和删除都不需要再去维护标签关系，而查询前期可以直接用 extensionClient.list 或者参考文章使用 indexer，建立 labels 缓存，等后续出了 informer 机制也可以解决，不应该为了标签去做大量维护工作得不偿失。
