### ISSUE TITLE
请问下，我设置好瞬间这个插件后，怎么不显示

### ISSUE THREAD

**Issue by libashanxi** [halo-sigs/plugin-moments#19]
![image](https://user-images.githubusercontent.com/65264574/234806191-e789d680-240a-4cd2-b03b-9ccaef674215.png)
菜单设置如上
![image](https://user-images.githubusercontent.com/65264574/234806385-65665227-04ae-4dcd-8f3e-e85331288677.png)
报错如上

小白请教下这是怎么回事

**Comment by guqing** [comment]
此主题适配了还没有发版本，可以下载 main 分支最新的主题包使用 https://github.com/guqing/halo-theme-higan/archive/refs/heads/main.zip
