### ISSUE TITLE
瞬间发布超链接不显示了

### ISSUE THREAD

**Issue by shy-share** [halo-sigs/plugin-moments#34]
![image](https://github.com/halo-sigs/plugin-moments/assets/50973219/3dce2d8c-0d8b-4cff-8100-c822a8de443e)
f12 查看的话 是有这个超链接的，只是没有显示出来而已
![image](https://github.com/halo-sigs/plugin-moments/assets/50973219/6693db04-415e-41cf-af99-34c9048a84bf)

**Comment by LIlGG** [comment]
主题端显示是由主题样式所控制的，需要主题进行处理。
