### ISSUE TITLE
瞬间  里面有评论，但是不显示评论数量

### ISSUE THREAD

**Issue by Jehol1983** [halo-sigs/plugin-moments#39]
<img width="355" alt="image" src="https://github.com/halo-sigs/plugin-moments/assets/75714146/cc6eaa4b-59c8-4d6a-a5b3-5482e2bbcc24">

**Comment by ruibaby** [comment]
这里的评论量显示应该不是这个插件控制的，建议向具体的主题提交 issue 。

相关文档：https://halo.run/store/apps/app-SnwWD#:~:text=th%3Ablock%3E-,%E7%B1%BB%E5%9E%8B%E5%AE%9A%E4%B9%89,-MomentVo
