### ISSUE TITLE
看了鱼佬的即刻支持播放器和图册，大佬能适配下不🥰

### ISSUE THREAD

**Issue by lzrh123jia** [halo-sigs/plugin-moments#40]
![9465d2739bb444fd873d7618b96c177](https://github.com/halo-sigs/plugin-moments/assets/90361939/93faad84-9585-4913-a347-1221b9361387)
![0215ad5065b3e34368bbc61e08e3017](https://github.com/halo-sigs/plugin-moments/assets/90361939/70ef5d41-e817-4da8-b2b9-e78c8a8b5620)

**Comment by LIlGG** [comment]
瞬间目前是支持最大 9 张图片的，需要主题去适配。播放器建议使用 iframe。
