### ISSUE TITLE
使用代码块，会超出限制

### ISSUE THREAD

**Issue by sunheyi6** [halo-sigs/plugin-moments#41]
1. ![image](https://github.com/halo-sigs/plugin-moments/assets/50973219/bd02a3a4-97ff-4697-b331-4901d2b1e5a2)
地址：https://shyblog.world/moments
2. 我有37个瞬间数据，为什么这里只显示这几个，现在是还没有分页的功能吗？

**Comment by ruibaby** [comment]
这个问题应该和主题有关，和此插件没有关系。

分页可以在插件设置中设置默认条数。

/kind support

**Comment by sunheyi6** [comment]
> 这个问题应该和主题有关，和此插件没有关系。
> 
> 分页可以在插件设置中设置默认条数。
> 
> /kind support

好的，我看到了，瞬间插件 详情可以选择显示多少条，具体分页应该是由主题来适配的
