### ISSUE TITLE
Releases 1.2.0 中的CSS文件内容异常

### ISSUE THREAD

**Issue by Dyzmj** [halo-sigs/plugin-moments#42]
Releases 1.2.0  中的 style.css 文件里没有 ".moment .tag" 的样式内容，导致tag标签样式无法正常显示。

我看guqing的网站里引用的地址是 "https://guqing.xyz/themes/guqing-higan/assets/dist/style.css?v=2.4.0"，这个版本的CSS文件复制过去后 tag 就正常显示了

**Comment by ruibaby** [comment]
目前插件并不会为主题提供标签的样式，所以可能需要主题主动适配。

比如：https://ryanc.cc/moments?tag=%E6%9D%82%E8%AE%B0

/kind support
