### ISSUE TITLE
在控台里发布瞬间如何选择标签

### ISSUE THREAD

**Issue by marsblackkk** [halo-sigs/plugin-moments#45]
<img width="863" alt="image" src="https://github.com/halo-sigs/plugin-moments/assets/94500161/e2599a4f-f746-41e4-a5fc-5b1a63eaa314">
使用主题: Walker

**Comment by LIlGG** [comment]
使用 `#` 号即可弹出标签列表，可在其内进行选择。如果目标标签还未创建，则直接输入 `#xxx` 后空格即可，发布瞬间后会自动创建。如下所示

<img width="884" alt="image" src="https://github.com/halo-sigs/plugin-moments/assets/31335418/90adcc41-7563-4ac8-aeef-8c629d295997">

**Comment by marsblackkk** [comment]
ありがとう！
