### ISSUE TITLE
请求多加入一种上传资源的方式。

### ISSUE THREAD

**Issue by ExoticSkywing** [halo-sigs/plugin-moments#46]
瞬间这个插件，目前除了iframe，引入音视频资源只有一种方式，就是通过附件上传，通过附件不仅麻烦，还占用机器本地资源。能不能像halo后台编辑文章一样，直接通过链接来引入资源，这不更方便吗？大家用这个都是自备图床的人。或者说支持更多html标签也可以。

**Comment by ruibaby** [comment]
最新版本已支持。

/close
