### ISSUE TITLE
瞬间有序列表 bug

### ISSUE THREAD

**Issue by yuanzhixiang** [halo-sigs/plugin-moments#50]
瞬间有序列表在 编辑时，预览时，主题展示 出现不同的状态，编辑时是正常的 markdown，预览时 markdown 中的缩进消失了，主题展示时有的缩进有，有的缩进没有，序号出现了重复

下面的三张图片展示了同一段文字在不同场景时的效果

### 编辑时

<img width="889" alt="图片" src="https://github.com/halo-sigs/plugin-moments/assets/25138766/00af6f8a-6d8c-4fa7-8132-ea3d3e287a20">

### 预览时

<img width="847" alt="图片" src="https://github.com/halo-sigs/plugin-moments/assets/25138766/4ad699d3-bb55-46dc-9494-28ace0b1cd4c">

### 主题展示

<img width="871" alt="图片" src="https://github.com/halo-sigs/plugin-moments/assets/25138766/c654aa44-7b51-44ea-90ed-3af9187c6109">

**Comment by LIlGG** [comment]
预览时是由于没有样式，与 #48 的原因相同，主题端序号出现了重复应该是主题端的问题，建议向主题作者提交 issue。

/triage duplicate
/close
