### ISSUE TITLE
更新到1.4.0后halo控制台出现“加载插件入口文件失败”

### ISSUE THREAD

**Issue by myhloli** [halo-sigs/plugin-moments#61]

**Comment by myhloli** [comment]
halo版本 2.11.2
构建方式 1panel应用市场版本

**Comment by myhloli** [comment]
重新测试了下，好像是360极速浏览器的问题，换成edge之后就正常了
<img width="969" alt="屏幕截图 2023-12-09 151741" src="https://github.com/halo-sigs/plugin-moments/assets/11393164/091c082b-6dde-43d2-a624-ae005debfc14">
这个是360极速浏览器的报错信息
![屏幕截图 2023-12-09 151907](https://github.com/halo-sigs/plugin-moments/assets/11393164/a1b3d333-8d40-4eef-af1d-e847809500f7)

**Comment by ruibaby** [comment]
内核过旧，可能无法支持 Halo 中用的一些 JS 新 API。
