### ISSUE TITLE
评论通知问题

### ISSUE THREAD

**Issue by chengzhongxue** [halo-sigs/plugin-moments#67]
会给每个带有瞬间权限的用户发一条通知
![image](https://github.com/halo-sigs/plugin-moments/assets/89380218/b8f29247-0273-4f7c-acaf-e801d3dfcfb9)

**Comment by chengzhongxue** [comment]
这个应该是瞬间更新多用户之前的版本有这个问题，后面的我还没试过，晚点我试试

**Comment by guqing** [comment]
> 这个应该是瞬间更新多用户之前的版本有这个问题，后面的我还没试过，晚点我试试

那我知道了，确实有这个问题，因为之前没有多用户，所以瞬间的评论事件订阅是订阅所有瞬间，如果有多人发布瞬间确实会出现此问题
/remove-triage needs-information
