### ISSUE TITLE
更新halo到2.11.2后出现新增“瞬间”前台不显示问题

### ISSUE THREAD

**Issue by carolcoral** [halo-sigs/plugin-moments#70]
* halo: 2.11.2
* 瞬间: 1.4.0

### 问题描述
当halo更新到2.11.2 后，在瞬间中新增的`瞬间`内容在前台不会正常展示。只会展示历史的`瞬间`内容。
通过查看F12发现代码没有正常展示出来。是否存在新版本的兼容性问题？
通过查看halor日志发现后台没有报错。

### 相关截图
<img width="1332" alt="image" src="https://github.com/halo-sigs/plugin-moments/assets/8952687/b8347823-9806-40a9-ba36-715a1539f172">

<img width="1599" alt="image" src="https://github.com/halo-sigs/plugin-moments/assets/8952687/8b2150ec-034d-404a-88c4-71adce800caa">

**Comment by LIlGG** [comment]
查看 `瞬间插件 -> 基本设置 -> 瞬间列表显示条数`，这里的设置是否正确。如下所示

<img width="1111" alt="image" src="https://github.com/halo-sigs/plugin-moments/assets/31335418/592d3239-6714-4456-9654-5e0d346e8e0e">

如果无法展示完全，可能是主题的问题。建议向主题仓库提交 issue。

**Comment by carolcoral** [comment]
> 同样问题，请问解决了吗

解决了，主题增加修复兼容。因为新版本的瞬间在 `<span>` 标签中增加了`style`导致了无法正确去处理
