### ISSUE TITLE
1.5版本之前的数据删掉会无限请求列表

### ISSUE THREAD

**Issue by chengzhongxue** [halo-sigs/plugin-moments#85]
![image](https://github.com/halo-sigs/plugin-moments/assets/89380218/6e04561f-b508-4f0e-be73-7198d78f3c22)
![image](https://github.com/halo-sigs/plugin-moments/assets/89380218/aa9fa535-c1f2-4a8f-83a7-c6879e369446)

**Comment by guqing** [comment]
Hi @chengzhongxue ，感谢提出此问题🎉，已经发布了一个修复版本 v1.5.1 到应用市场，更新后之前标记为删除但没有删掉的数据会自动被删除无需做任何处理
