### ISSUE TITLE
Halo 最新 main（20d80f8） 分支无法正常运行此插件

### ISSUE THREAD

**Issue by ruibaby** [halo-sigs/plugin-moments#89]
main 分支：https://github.com/halo-dev/halo/commit/20d80f8

日志：

[halo-log-2024-03-10 19_55.log](https://github.com/halo-sigs/plugin-moments/files/14550107/halo-log-2024-03-10.19_55.log)

看日志似乎和 https://github.com/halo-dev/halo/commit/a8627cbc2f15d0b056b27a1b6ea57b1726af7efd 升级了 pf4j 的版本有关。

**Comment by guqing** [comment]
此问题与 pf4j 无关,应该是改了返回值类型此插件不兼容了导致的
/assign

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/5507 中修复。

/close
