### ISSUE TITLE
瞬间输入框内容无法删除

### ISSUE THREAD

**Issue by wxyShine** [halo-sigs/plugin-moments#91]
- 外部访问地址: https://www.wxy97.com/
- 启动时间: 2024-04-02 14:08
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: PostgreSQL / 16.2 (Debian 16.2-1.pgdg120+2)
- 操作系统: Linux / 6.1.0-10-amd64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [豆瓣](https://github.com/chengzhongxue/plugin-douban)
  - [Webhook](https://github.com/wxyShine/halo-plugin-webhook)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - AI 助手
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)

![image](https://github.com/halo-sigs/plugin-moments/assets/42802152/8ff2ae6f-a566-43fe-b030-7aba5403b869)

1.瞬间输入框内容无法删除
2.字体样式（字号等无法修改

**Comment by LIlGG** [comment]
建议提交 issue 时，将不同的问题单独提交，这样可以更好的追踪问题。

/kind bug
