### ISSUE TITLE
瞬间什么时候支持 md 语法，使用![]()图片嵌入，这对我很重要

### ISSUE THREAD

**Issue by king-zhangbn** [halo-sigs/plugin-moments#93]
我目前图片全部在图床上，我不想在本地留下任何图片元素，能否支持外链直接调用，附近库有外链的话可以大大减少资源的占用

**Comment by LIlGG** [comment]
瞬间本身是基于富文本编辑器的，而 ![]() 是 Markdown 编辑器才具有的功能，因此并不支持。

不过可以考虑为 image 扩展增加 / 的命令方式，类似于视频和音频一样。

<img width="868" alt="image" src="https://github.com/halo-sigs/plugin-moments/assets/31335418/2d241f13-b56e-4878-84be-f0f9c863f7e9">

/kind feature

**Comment by king-zhangbn** [comment]
这瞬间要不改成 md 编辑器吧，这样瞬间的花样就多了！
