### ISSUE TITLE
后台查看图片，放大图片不会显示完全

### ISSUE THREAD

**Issue by 52lemon6** [halo-sigs/plugin-moments#94]
如图中所示，在缩略图的状态下，能完全的看到票和左下角的水印，放大后看就看不到了
![image](https://github.com/halo-sigs/plugin-moments/assets/40059643/88d921d7-87f7-42a6-8b1e-2b39117f112c)
![image](https://github.com/halo-sigs/plugin-moments/assets/40059643/08ac258a-d451-4b13-bc9a-1776eca72c29)

**Comment by LIlGG** [comment]
确实存在这样的问题，放大的图片裁剪了原有的图片。

/kind bug
