### ISSUE TITLE
Finder with name 'momentFinder' is already registered

### ISSUE THREAD

**Issue by qwq202** [halo-sigs/plugin-moments#95]
![image](https://github.com/halo-sigs/plugin-moments/assets/146629280/846607c5-129f-48c5-ae0a-e92425511ab2)
这种情况该怎么办，我在升级后就出现了这种状况，
原本用的是这个pix主题提供的瞬间插件，不小心点到升级了就这样了
[e59f95055bdcbee81fcac4d5012216ad.zip](https://github.com/halo-sigs/plugin-moments/files/15064168/e59f95055bdcbee81fcac4d5012216ad.zip)

**Comment by LIlGG** [comment]
感谢反馈，此问题应该与 https://github.com/halo-dev/halo/issues/5615 有关，将会在 PR https://github.com/halo-dev/halo/pull/5855 中进行修复。

这个修复应当会在 2.15.1 中发布，可以随时关注。

**Comment by LIlGG** [comment]
感谢反馈，可能需要提供一下日志来供我们排查此问题。

/kind support
